### ISSUE TITLE
Focused wrapper div gets border

### ISSUE THREAD

**Issue by ivos** [Chrisui/react-hotkeys#23]
&lt;HotKeys/> wraps its children into a &lt;div tabIndex="-1"/>. When the user clicks the form outside of any control, the whole form gets a weird focused border created by the browser (Chrome has a particularly visible one).

Is there a way to prevent this?

Some probably stupid ideas:
- Push the border somehow on the very limits of the viewport to make it less eye-catching.
- Add code to the &lt;div/> to drop focus after it receives it.

**Comment by Chrisui** [comment]
You can use css :)

`:focus { outline: 0; }` off the top of my head!

**Comment by ivos** [comment]
Thanks! Works for me with:

div[tabindex="-1"]:focus {
	outline: 0;
}

**Comment by ivos** [comment]
I still wonder. I didn't create the &lt;div/> in my app's code, so is it right that I style it there? Is everyone who uses react-hotkeys supposed to include the above style in their app's css?

Seems to me like a workaround, not a solution. The &lt;div/> is there to trap the focus event, not to produce any visible effects. Could it be that [this line](https://github.com/Chrisui/react-hotkeys/blob/master/lib/FocusTrap.js#L22) might become something like:

    <Component tabIndex="-1" style={{outline: 0}} {...this.props}>

**Comment by Chrisui** [comment]
It's an interesting thought and I can see where you're coming from.

**Comment by Chrisui** [comment]
Sorry accidentally closed that too soon :P

**Comment by Chrisui** [comment]
...Carrying on...  The visible effect is a browser default and accessibility feature (which is sort of valid when you're making focusable areas) so I'm put off from adding hard overrides when a small bit of css provides much greater flexibility and predictability from the consumer side.

The real issue here is that we output that mentioned `div` at all (creating extra hierarchy in the dom) which is what I've had in my head to solve with the next major version of the library pretty much for the past year. Been on a winter break but hopefully, work permitting, this will be coming soon!

Future API will remove the need for this meaning you're in total control of the rendered output.

**Comment by ivos** [comment]
If a future version will make do without the &lt;div/> at all that would be great.

In the meantime I'm quite happy with the css. I was just trying to help. Thanks for your support.

**Comment by opichals** [comment]
It could probably be solved along with the mousetrap delegation refactoring mentioned in https://github.com/chrisui/react-hotkeys/issues/2.

We have hit both this issue breaking flexbox styling and the delegation issue possibly giving us performance headaches.

**Comment by amirmohsen** [comment]
Can you please include this problem and the workaround in the readme as a "gotcha"? I spent quite a bit of time trying to figure out what was causing the outline.

**Comment by acnebs** [comment]
As far as I can tell, you can rid yourself of the enclosing `<div />` by using the Fragment feature as of React 16. Do this by adding `component="document-fragment"` to you `<HotKey />` component, as so:

`<HotKey component="document-fragment" handlers={handlers}>`

You'll probably need to add a `tabindex="-1"` to the immediate child component of your `<HotKey />` component to replicate previous behavior, but this is working well for me without side-effects.
