### ISSUE TITLE
Usage with enzyme tests

### ISSUE THREAD

**Issue by mshwery** [chrisui/react-hotkeys#30]
I'm not sure if you've encountered this – but I can't seem to have `react-hotkeys` catch _simulated_ events on react components, like with enzyme's `simulate` method.

**Comment by chrisui** [comment]
Not entirely sure how simulated events work within react testing but i have a suspicion they ignore the DOM altogether and use the reimplemented event system under the hood.

In this case, since Mousetrap is looking for DOM events, you probably need to trigger events separately on the DOM rather than using simulated React events.

**Comment by chrisui** [comment]
Sorry for the delay in response btw, I've been on holiday!

**Comment by chrisui** [comment]
Closing this since there was no response.

**Comment by ahuth** [comment]
For anyone coming across this, I've verified that triggering an actual DOM event works.

Something like this will work:

```js
const event = new Event('keydown');
event.keyCode = 39;
component.getDOMNode().dispatchEvent(event);
```

**Comment by hkmarques** [comment]
Just to add to the previous response, if you need modifier keys, do either
```
event.ctrlKey = true;
event.shiftKey = true;
event.metaKey = true;
```
And if you're using the explicit `attach`, be sure to use an appropriate element to dispatch the event from. Also, if you're using `attach` just to fake a global event while it's not present in the stable release, use `document` both to attach it to and to dispatch the event from instead of `window` as your test will just silently fail because of the absent window object out of the box.
