### ISSUE TITLE
Allow HotKeys component to autofocus

### ISSUE THREAD

**Issue by megapctr** [chrisui/react-hotkeys#41]
I'd like to be able to have HotKeys autofocus, so I can easily set up global hotkeys.
Proposal: when given an `autoFocus` prop, HotKeys would render FocusTrap with `ref={n => n && setTimeout(() => n.focus())}`.

**Comment by mendelk** [comment]
+1. See also #25, and in particular [this comment](https://github.com/chrisui/react-hotkeys/issues/25#issuecomment-212343793)

**Comment by chrisui** [comment]
Hey man cheers for the request!

I definitely want to make it easier for global hotkeys as it seems it's quite a popular request and not obvious how to do it. I'm wondering whether `autofocus` is the right name though since this usually implies it will receive focus *initially* but *can* lose it. Ie. if you "auto focus" an input you focus on mount but it's not *always* focused.

Theoretically this should be possible on `Hotkeys` using [these two props](https://github.com/chrisui/react-hotkeys/blob/master/lib/HotKeys.js#L37-L38)

Just to check could you, on your global top level `Hotkeys` component, try the following usage:

```jsx
<Hotkeys focused={true} attach={window} ... />
```

This is a work around if it works and I will look to make it easier (and document!!) for global hotkeys. My proposal would be for a prop `global={true}` which implies it catches *all* events anywhere on the page and doesn't worry about "focus".

**Comment by megapctr** [comment]
Yup it works perfectly, thanks!

**Comment by megapctr** [comment]
BTW, what if I have some local hotkeys within the global hotkeys scope? will it fire event for both hotkey maps?

**Comment by chrisui** [comment]
Theoretically if the local scope is focused and the *exact same* hotkey sequence is triggered the local one will take precedence.

Ive been toying with the idea of allowing you to say "I actually don't want to handle this so pass it on" inside the handler via some "continuePropagation" api but for now you can at least just call props upwards yourself.

**Comment by megapctr** [comment]
That's not my case, actually I'm glad one action cancels out another.

Is `focused attach={window}` an experimental api, or something I can keep using?

**Comment by chrisui** [comment]
Yup I implemented that believing it's the most sensible default! :) it's
half of what makes this library useful out the box I reckon.

That api will definitely be supported for the foreseeable future as an
escape hatch with a more modern api on top at some point.

**Comment by rajnishcoder** [comment]
> Hey man cheers for the request!
> 
> I definitely want to make it easier for global hotkeys as it seems it's quite a popular request and not obvious how to do it. I'm wondering whether `autofocus` is the right name though since this usually implies it will receive focus _initially_ but _can_ lose it. Ie. if you "auto focus" an input you focus on mount but it's not _always_ focused.
> 
> Theoretically this should be possible on `Hotkeys` using [these two props](https://github.com/chrisui/react-hotkeys/blob/master/lib/HotKeys.js#L37-L38)
> 
> Just to check could you, on your global top level `Hotkeys` component, try the following usage:
> 
> ```js-jsx
> <Hotkeys focused={true} attach={window} ... />
> ```
> 
> This is a work around if it works and I will look to make it easier (and document!!) for global hotkeys. My proposal would be for a prop `global={true}` which implies it catches _all_ events anywhere on the page and doesn't worry about "focus".

Hi, where I can find list of all attributes like `keyMap, focused,  attach` ?

**Comment by greena13** [comment]
Hi rajnishcoder,

You can take a look at the [TypeScript definitions](https://github.com/greena13/react-hotkeys/blob/v1.1.4/index.d.ts#L24) for the `<HotKeys>` component, for the latest stable version.

Or for the new pre-release, take a look at the [HotKeys API documentation](https://github.com/greena13/react-hotkeys#hotkeys-component-api) - in this and all future versions, `focused` and `attached` are both replaced by the [GlobalHotkeys API](https://github.com/greena13/react-hotkeys#globalhotkeys-component).
